### ISSUE TITLE
Page jump & random download

### ISSUE THREAD

**Issue by 0xh3LL0** [xuzhengyi1995/Bookwalker_Downloader#3]
manga link: https://bookwalker.jp/de3b5fe365-32af-4b5b-9250-df9ae04a2a1d/
total page 163, but only 38 page downloaded, sometimes the page are skipped like from page 50 to 57, 82 to 133 and so on...
 
changes i made (aside from manga url, obviously):

RES = (1128, 1600)

LOADING_WAIT_TIME = 50

here is the error.png
![error](https://user-images.githubusercontent.com/23132217/79709622-e12df680-82ec-11ea-8083-eb6f23c0e197.png)

**Comment by xuzhengyi1995** [comment]
Thank you for your issue.

I have changed the method to move the page, you can fetch the new program and run it.
And normally `LOADING_WAIT_TIME` no need to be that long, 10 to 20 seconds is enough.

If there is still any problem, you can also add the `SLEEP_TIME` to 5 or 10 seconds to wait the new page loading, regarding to my network situation 2 seconds is enough.

And the new version we must use cookies to login, because the headless chrome is faster and can give an exact size of windows.

Now it's working better than before:

![image](https://user-images.githubusercontent.com/29002064/79721529-13534e80-8315-11ea-9a87-47ac7c7a159a.png)

I'm still working on the `Readme.md`, maybe you can find it after 10 minutes.

I'll also recommend you [Bookworm](https://github.com/aaa4xu/bookworm), this also works.

**Comment by 0xh3LL0** [comment]
thank you, i'll try later...

about bookworm,
where do i need to put my username, password and content id?

**Comment by xuzhengyi1995** [comment]
> thank you, i'll try later...
> 
> about bookworm,
> where do i need to put my username, password and content id?

For Bookworm, you can run the script and then input or copy the username/password or content id after the prompt.

**Comment by 0xh3LL0** [comment]
now i constantly got an error...
though i renew the cookies by logout and login again,
here is the error.png

edit:
in case this important,
win 10 64 bit, python 3.7.3 64 bit, chrome 81

![error](https://user-images.githubusercontent.com/23132217/79731316-4fd67880-831c-11ea-81e3-b24d5352333d.png)

**Comment by xuzhengyi1995** [comment]
> now i constantly got an error...
> though i renew the cookies by logout and login again,
> here is the error.png
> 
> edit:
> in case this important,
> win 10 64 bit, python 3.7.3 64 bit, chrome 81
> 

Please check is the cookies are right or not, the cookies should be get by `F12` but not by using the JavaScript.

Go to [My page](https://member.bookwalker.jp/app/03/my/profile), and press `F12` to open the `DevTools`, go to `Network` and then refresh the page, you can copy the cookies as the image below:

![image](https://user-images.githubusercontent.com/29002064/79736407-50770b00-832c-11ea-9be0-eb80098e0d10.png)

If this is not the problem of the cookies, you can check is the manga URL is right or not, the manga URL should like something below copied from `holdBooks` and the button `この本を読む`:

https://member.bookwalker.jp/app/03/webstore/cooperation?r=BROWSER_VIEWER/3b5fe365-32af-4b5b-9250-df9ae04a2a1d/https%3A%2F%2Fbookwalker.jp%2FholdBooks%2F

**Comment by 0xh3LL0** [comment]
oh, stupid me, i'm using my different account...

anyway, is something like this normal?
although the manga fully downloaded
![Screenshot 549](https://user-images.githubusercontent.com/23132217/79823945-24f13080-83bf-11ea-9553-2e0f3d414d4c.png)

**Comment by xuzhengyi1995** [comment]
> oh, stupid me, i'm using my different account...
> 
> anyway, is something like this normal?
> although the manga fully downloaded
> ![Screenshot 549](https://user-images.githubusercontent.com/23132217/79823945-24f13080-83bf-11ea-9553-2e0f3d414d4c.png)

This is normal, these messages are from the Browser and JavaScript, never mind these kinds of error messages if the manga can be downloaded normally, because normally the Browser and the JavaScript will handle it. Thank you.
